const mainPath = '/';
export const Constants = {
  LOCATION_URL: window.location.protocol + '//' + window.location.hostname,
  // LOCATION_URL: 'https://sit-opl.instantmseloans.in' + '/user/management',
  // DOMAIN_URL: 'https://sit-hsbc.instantmseloans.in',
  // LOCATION_URL:"http://localhost:4200",
  cwjs: '26f1ac75f77c22ebc66e2359c13ea9955ebd5e2bd7fbe50e5b3ac2977a772302',
  IS_ENCRYPTION: true,
  IS_LOCAL: true,
  BussinessType: {
    EXISTING_BUSINESS: 1,
    NEW_TO_BUSINESS: 2,
    ONE_PAGER_EXISTING_BUSINESS: 4,
    MUDRA_LOAN: 10,
    ODOP_LOAN: 22
  },

  RoleType: {
    NON_BUSSINESS_USER: 1,
    BUSSINESS_USER: 2,
  },

  CustomerType: {
    ETB: 1,
    TARGET: 2,
    PROSPECTS: 3,
    FDI: 4,
    ODI: 5,
    ECB: 6,
  },
  CustomerTypeById: {
    1: "ETB",
    2: "TARGET",
    3: "PROSPECTS",
    4: "FDI",
    5: "ODI",
    6: "ECB",
  },

  SocketFilterRequestTypeForDS: {
    GET_CAMPAIGN_DETAILS: 1,
    GET_OPPORTUNITY_DASHBOARD_DATA: 2,
  },

  SourceNameForCampaign: {
    ETB: "ETB",
    NTB: "NTB",
    PR: "PR",
  },

  INACTIVE_CUSTOMER: 8,
  CLEAN_FILTER_LIST_MASTER: "filterListMaster", // to avoid api call on reset.

  FILTER_JSON_EXISTING: "filterJsonExiting",
  SELECTED_COLUMNS_EXISTING: "selectedColumnsExisting",
  FILTER_LIST_MASTER_EXISTING: "filterListMasterExiting",
  FILTER_JSON_TARGET: "filterJsonTarget",
  SELECTED_COLUMNS_TARGET: "selectedColumnsTarget",
  FILTER_JSON_FIND_PROSPECT: "filterJsonFindProspect",
  FILTER_LIST_MASTER_TARGET: "filterListMasterTarget",
  SELECTED_COLUMNS_FIND_PROSPECT: "selectedColumnsFindProspect",
  TOP_BAR_FILTER_LIST_EXISTING: "topBarFilterListExiting",
  TOP_BAR_FILTER_LIST_TARGET: "topBarFilterListTarget",
  TOP_BAR_FILTER_LIST_FIND_PROSPECT: "topBarFilterListFindProspect",

  // Hierarchy filter state keys
  HIERARCHY_FILTER_EXISTING: "hierarchyFilterExisting",
  HIERARCHY_FILTER_TARGET: "hierarchyFilterTarget",
  HIERARCHY_FILTER_WALLET: "hierarchyFilterWallet",
  HIERARCHY_FILTER_PORTFOLIO: "hierarchyFilterPortfolio",

  FILTER_LIST_MASTER_PROSPECTS: "filterListMasterProspects",

  ROUTE_URL: {
    CONSENT: mainPath + 'mconsent',
    MODULE_SELECT: mainPath + 'mModuleSelect',
    GST_DETAILS: mainPath + 'mGstDetails',
    ITR_DETAILS: mainPath + 'mItrDetails',
    BANK_STATEMENT: mainPath + 'mBankStatement',
    KEY_PERSON: mainPath + 'mKeyPerson',
    ONE_FORM: mainPath + 'mOneForm',
    BRANCH_SELECT: mainPath + 'mBranchSelect',
    VIEW_GST_ANALYSIS: mainPath + 'rmGSTAnalysisView'
  },
  PRODUCT_ID: 'productId',

  UserType: {
    FUNDSEEKER: 1,
    FUNDPROVIDER: 2,
    SERVICEPROVIDER: 3,
    NETWORKPARTNER: 4
  },

  REGEX: {
    ALLOW_NUMERIC_DECIMAL_NEGATIVE: /[^0-9.-]/g, // Allows numbers, decimals, and negative signs
    ALLOW_NUMERIC_DECIMAL: /[^0-9.]/g, // Allows numbers and decimals only
  },

  DATE_FORMAT: {
    TRAIL_TIMESTAMP: 'dd-MMM-yy h:mm a' // Format: 15-Jan-24 2:30 PM
  },

  autoSavedTime: 300000,
  NA: 'NA',
  APPLICATION_ID: 'applicationId',
  APP_PROPOSAL_ID: 'app_proposal_id',
  FP_PRODUCT_ID: 'fpProductId',
  SP_CLIENT_ID: 'clientId',
  NP_CLIENT_ID: 'clientId',
  FP_CLIENT_ID: 'clientId',
  CLIENT_NAME: 'clientName',
  SP_USER: "spUser",
  NP_USER: "npUser",
  FP_USER: "fpUser",
  PERMISSION: "permission",
  USER_PERMISSION: "userPermission",
  BUSINESS_TYPE_ID: "businessTypeId",
  LOAN_TYPE_ID: "loanTypeId",
  SUB_LOAN_TYPE_ID: "subLoanTypeId",
  TL_LESS_TWO: 20000000,
  APPLICATION_NAME: "applicationName",
  APPLICATION_CODE: "applicationCode",

  AL_DEALER_BANK_LIST: ["16"],
  UPLOAD_FROM: {
    FINAL_UPLOAD: 1,
    DDR_UPLOAD: 2
  },
  userType: {
    1: "Fund Seeker",
    2: "LENDER",
    3: "Service Provider",
    4: "Network Partner"
  },
  uploadUserType: {
    APPLICANT_TYPE: "applicant",
    CO_APPLICANT_TYPE: "coApplicant",
    GUARANTOR_TYPE: "guarantor",
    CORPORATE_APPLICANT: "corpApplicant",
    CORPORATE_COAPPLICANT: "corpCoApplicant"
  },
  retailUserType: {
    Applicant: 1,
    CoApplicant: 2,
    Guarantor: 3
  },
  user: {
    fs: 1,
    fp: 2,
    sp: 3,
    np: 4
  },
  userManagementType: {
    allUser: 1,
    allOffice: 2,
    tierMapping: 3,
  },
  httpAndCookies: {
    ACTK: "tk_ac",
    RFTK: "tk_rc",
    USNM: "ur_cu",
    LGTK: "tk_lg",
    COOKIES_OBJ: "ck_obj",
    USERTYPE: "usr_type",
    ORGID: "usr_orgId",
    ROLEID: "usr_role_id",
    CAMPIGN_CODE: 'campaignCode',
    CAMPIGN_TYPE: 'type',
    NEW_ROLE_ID: "new_role_id",
    BUSINESS_TYPE_ID: "business_type_id",
    LOAN_TYPE_ID: "loan_type_id",
    USER_PERMISSION: "up_data",
    ENV_ORG_ID: 'envOrgId',
    USER_ID: "user_id",
    USER_NAME: "userName",
    SCHEME_ID: 'scheme_id',
    TABID: "tab_id",
    ACCESS_PATH: 'accessPath',
    IS_SHOW_AUDIT_API: 'isShowAuditAPI',
    PLATFORM_ID: 'platForm_id',
    IS_SHOW_NEW_CAM_KFS_BTN: 'isShowNewCAMKFSButton',
    REF_TYPE_FOR_AUDIT: "refType",
    ANALYSIS_MASTER_ID: "mstId",
    REF_ID_FOR_AUDIT: "refId",
    APPLICATION_ID: 'applicationId',
    CIBIL_ID: "cibilId",
    MSAL_ACCESS_TOKEN: "msalAccessToken",
    AUTHORIZATION: "Authorization",
    BEARER: "Bearer ",
    IS_INDIVIDUAL: "isIndividual",
    ACCESSIBLE_BUTTONS_CSS: 'accessibleButtonsCss',
    EMP_CODE: 'employeeCode',
    ROLE_TYPE: 'roleType',
    CMP_SEARCH_DATA: 'allSearchCustomerData',
    US_PR: 'uspr',
    PR_DASHBOARD_FILTER_DATA_SUMMARY: 'prDashboardFilterDataSummary',
    PR_DASHBOARD_FILTER_DATA_COMPARISON: 'prDashboardFilterDataComparison',
  },

  SUCCESS_MESSAGE: "Saved Successfully",
  CONNECT_FLOW_TYPE_ID: "connectFlowTypeId",

  // FRAMES
  frames: {
    corporate: {
      achievementDetails: "app/fund-seeker/popup/htmls/achievementDetails.html|achievementDetailsCtrl",
      collateralSecurity: "app/fund-seeker/popup/htmls/collateralSecurity.html|collateralSecurityCtrl",
      costOfEstimates: "app/fund-seeker/popup/htmls/costOfEstimates.html|costOfEstimatesCtrl",
      creditRating: "app/fund-seeker/popup/htmls/creditRating.html|creditRatingCtrl",
      currentFinancialArrangements: "app/fund-seeker/popup/htmls/currentFinancialArrangements.html|currentFinancialArrangementsCtrl",
      existingLoanDetails: "app/fund-seeker/popup/htmls/existingLoanDetails.html",
      futureProjections: "app/fund-seeker/popup/htmls/futureProjections.html|futureProjectionCtrl",
      meansOfFinace: "app/fund-seeker/popup/htmls/meansOfFinace.html|meansOfFinaceCtrl",
      owenershipDetails: "app/fund-seeker/popup/htmls/owenershipDetails.html|owenershipDetailsCtrl",
      pastFinancials: "app/fund-seeker/popup/htmls/pastFinancials.html|pastFinancialsCtrl",
      productDetails: "app/fund-seeker/popup/htmls/productDetails.html|productDetailsCtrl",
      reopenapplication: "app/fund-seeker/popup/htmls/re-openpopup.html",
      promotersBackgroundDetails: "app/fund-seeker/popup/htmls/promotersBackgroundDetails.html|promotersBackgroundDetailsCtrl",
      directorsBackgroundDetails: "app/fund-seeker/popup/htmls/directorsBackgroundDetails.html|directorsBackgroundDetailsCtrl",
      guarantorDetails: "app/fund-seeker/popup/htmls/guarantorDetails.html|guarantorDetailsCtrl",
      associatedConcern: "app/fund-seeker/popup/htmls/associatedConcern.html|associatedConcernCtrl",
      monthlyTurnover: "app/fund-seeker/popup/htmls/monthlyTurnover.html|monthlyTurnoverCtrl",
      fpMatcheDetails: "app/fund-provider/htmls/pop-up/fp-pop-up-view.html|fpMatchesPopupCtrl",
      proposedProductDetailsNTB: "app/fund-seeker/popup/htmls/proposedProductDetailsNTB.html|proposedProductDetailsNTBCtrl",
      guarantorDetailsNTB: "app/fund-seeker/popup/htmls/guarantorDetailsNTB.html|guarantorDetailsCtrlNTB"
    },
    retail: {
      bankAccountHeld: "app/fund-seeker/retail/popup/htmls/bankAccountHeld.html|bankAccountHeldCtrl",
      creditCards: "app/fund-seeker/retail/popup/htmls/creditCards.html|creditCardsCtrl",
      existingLoan: "app/fund-seeker/retail/popup/htmls/existingLoan.html|existingLoanCtrl",
      fixedDeposits: "app/fund-seeker/retail/popup/htmls/fixedDeposits.html|fixedDepositsCtrl",
      otherCurrentAssets: "app/fund-seeker/retail/popup/htmls/otherCurrentAssets.html|otherCurrentAssetsCtrl",
      otherIncomeDetails: "app/fund-seeker/retail/popup/htmls/otherIncomeDetails.html|otherIncomeDetailsCtrl",
      reference: "app/fund-seeker/retail/popup/htmls/reference.html|referenceCtrl",
      obligationDetail: "app/fund-seeker/retail/popup/htmls/obligationDetail.html|obligationDetailCtrl",
      incomeDetailsFinal: "app/fund-seeker/retail/popup/htmls/incomeDetailsFinal.html|incomeDetailsFinalCtrl",
      incomeDetailsProfile: "app/fund-seeker/retail/popup/htmls/incomeDetailsProfile.html|incomeDetailssil",
      financialDetails: {
        salaried: "app/fund-seeker/retail/popup/htmls/salariedEmpDetails.html|salariedEmpDetailsCtrl",
        selfBusiness: "app/fund-seeker/retail/popup/htmls/selfEmpDetails.html|selfEmpDetailsCtrl",
        agriculture: "app/fund-seeker/retail/popup/htmls/agriculturistEmpDetails.html|agriculturistEmpDetailsCtrl",
      },
      purchasePropertyDetails: "app/fund-seeker/retail/popup/htmls/purchasePropertyDetails.html|purchasePropertyDetailsCtrl",
      constructionPropertyDetails: "app/fund-seeker/retail/popup/htmls/constructionPropertyDetails.html|otherPropertyDetailsCtrl",
      renovationPropertyDetails: "app/fund-seeker/retail/popup/htmls/renovationPropertyDetails.html|otherPropertyDetailsCtrl",
      // securityDetails :
      // "app/fund-seeker/retail/popup/htmls/securityDetails.html|securityDetailsCtrl",
    },
    eligibility: {
      step1Eligibility: "app/common-pages/eligibility/step1Eligibility.html|step1EligibilityCtrl",
      congoEligibility: "app/common-pages/eligibility/congoEligibility.html|congoEligibilityCtrl",
      notEligible: "app/common-pages/eligibility/notEligible.html|notEligibleCtrl"

    }
  },
  framesUrl: {
    achievementDetails: "achievment_details",
    collateralSecurity: "security_corporate_details",
    costOfEstimates: "total_cost_of_project",
    creditRating: "credit_rating_organization_details",
    currentFinancialArrangements: "financial_arrangement_details",
    owenershipDetails: "ownership_details",
    existingProductDetails: "existing_product_details",
    proposedProductDetails: "proposed_product_details",
    promotersBackgroundDetails: "promotor_background_details",
    directorsBackgroundDetails: "director_background_details",
    futureProjections: "future_financial_estimate_details",
    meansOfFinace: "means_of_finance",
    pastFinancials: "past_financial_estimate_details",
    guarantorDetails: "guarantors_corporate_details",
    associatedConcern: "associated_concern_details",
    monthlyTurnover: "monthly_turnover_details",
    // Retail
    bankAccountHeld: "bank_account_held_details",
    creditCards: "credit_cards_detail",
    existingLoan: "existing_loan_details",
    fixedDeposits: "fixed_deposits_details",
    otherCurrentAssets: "other_current_asset_detail",
    otherIncomeDetails: "other_income_details",
    reference: "reference_retail_details",
    obligationDetail: "obligation_detail",
    empSalariedDetails: "emp_financial_details/salaried",
    empSelfDetails: "emp_financial_details/self",
    empAgriculturistDetails: "emp_financial_details/agriculturist",
    purchasePropertyDetails: "purchase_property_details",
    otherPropertyDetails: "other_property_details",
  },

  spPop: {
    addNewClient: "app/service-provider/htmls/add-new-client.html|addNewCtrl",
  },

  mcaPopUp: {
    mcaDecision: "app/common-utils/popup/htmls/Charges-code.html|mcaPopUpCtrl",
  },

  // FOR MATCHES CONSTANT
  proposalStatus: {
    PENDING: 1,
    ACCEPT: 2,
    HOLD: 3,
    DECLINE: 4,
    APPROVED: 5,
    PUBLISHED: 6,
    CANCEL: 7,
    SUGGESTION: 10,
    DISBURSED: 11,
    TODISBURSED: 12,
    PARTIALLY_DISBURSED: 13,
    REASON: 14,
    HANDSOFF: 15
  },

  ProposalStage: {
    PENDING: 0,
    PRIMARY: 1,
    FINAL: 2,
  },
  DenominationInAmount: {
    LAKHS: 100000,
    MILLIONS: 1000000,
    CRORES: 10000000,
    BILLIONS: 100000000,
    ABSOLUTE: 1
  },
  DenominationId: {
    LAKHS: 1,
    MILLIONS: 2,
    CRORES: 3,
    BILLIONS: 4,
    ABSOLUTE: 5
  }
  , NBFC_PRE_SANCTION_UPLOAD: {
    PAN: 603,
    ADDRESS: 604,
    PROJECTED_FINANCE: 610,
    CAMUPLOAD: 618,
  }, NBFC_PRE_DISBURSED_UPLOAD: {
    AGE_PROOF_DOCUMENT: 611,
    ID_PROOF_DOCUMENT: 612,
    ADDRESS_PROOF_DOCUMENT: 613,
    TRIPARTITE_AGREEMENT_LOAN_AGREEMENT: 605,
    SANCTION_LETTER: 606,
    APPLICATION_FORM: 614,
    DETAILED_ASSESSMENT_NOTE: 615,
    OTHER: 609,
    DEMAND_PROMISSORY_NOTE: 608,
    LETTER_OF_INTENT: 607
  }, NBFC_COLLECTION_UPLOAD: {
    NBFC_COLLECTION_DOCUMENT: 617,
  }, ProductDocumentMapping_WC: {
    PROFILE_PIC: 226,
    BROCHURE_OF_PROPOSED_ACTIVITIES: 1,
    CERTIFICATE_OF_INCORPORATION: 2,
    COPY_OF_PAN_CARD: 3,
    LAST_AUDITED_ANNUAL_REPORT: 9,
    SANCTION_LETTER_COPY: 10,
    LAST_IT_RETURN: 11,
    NETWORTH_STATEMENT_OF_DIRECTORS: 12,
    PROVISIONAL_FINANCIALS: 13,
    PAN_OF_DIRECTORS: 14,
    DETAILED_LIST_OF_SHAREHOLDERS: 15,
    PHOTO_OF_DIRECTORS: 16,
    CW_DPR_OUR_FORMAT: 4,
    CW_DPR_YOUR_FORMAT: 5,
    CMA: 7,
    COMPANYS_ACT_CMA: 8,
    FINANCIAL_MODEL: 6,
    BANK_STATEMENT: 294,
    IT_RETURN_DIRECTOR: 297,
    FINANCIALS_OF_SUBSIDIARIES: 20,
    ASSESSMENT_ORDERS: 22,
    DIRECTOR_ADDRESS: 302,
    DIRECTOR_RESOLUTION: 305,

    MOM_AOA: 18,
    DEBTORS_LIST: 308,
    GST_APPLIED: 312,
    LETTER_OF_INTENT: 315,
    RELEVANT_LICENSE: 21,
    SALES_TAX: 23,
    LATEST_TAX: 24,
    ENCUMBRANCE: 25,
    COPIES_TRUST_DEEDS: 26,
    MARKET_SURVEY_REPORT: 27,
    CONTINGENT_LIABILITIES: 323,

    FIELD_AUDIT_REPORT: 501,
    BANK_STATEMENT_OF_12_MONTHS: 505,
    FINANCIAL_FIGURE: 509,
    CENTRAL_TAX_REGISTRATION: 513,
    CENTRAL_EXCISE_RESGISTRATION: 517,
    VAT_REGISTRATION: 521,
    LIST_OF_DIRECTORS: 525,

    WC_PROFILE_PIC_COMPANY: 535,
    WC_SITE_OR_PROMOTERS_PHOTOS: 539
  },
  ProductDocumentMapping_TL: {
    PROFILE_PIC: 227,
    BROCHURE_OF_PROPOSED_ACTIVITIES: 28,
    CERTIFICATE_OF_INCORPORATION: 29,
    COPY_OF_PAN_CARD: 30,
    LAST_AUDITED_ANNUAL_REPORT: 36,
    SANCTION_LETTER_COPY: 37,
    LAST_IT_RETURN: 38,
    NETWORTH_STATEMENT_OF_DIRECTORS: 39,
    PROVISIONAL_FINANCIALS: 40,
    PAN_OF_DIRECTORS: 41,
    DETAILED_LIST_OF_SHAREHOLDERS: 42,
    PHOTO_OF_DIRECTORS: 43,
    CW_DPR_OUR_FORMAT: 31,
    CW_DPR_YOUR_FORMAT: 32,
    CMA: 34,
    COMPANYS_ACT_CMA: 35,
    FINANCIAL_MODEL: 33,
    BANK_STATEMENT: 295,
    IT_RETURN_DIRECTOR: 298,
    FINANCIALS_OF_SUBSIDIARIES: 47,
    ASSESSMENT_ORDERS: 49,
    DIRECTOR_ADDRESS: 303,
    DIRECTOR_RESOLUTION: 306,

    MOM_AOA: 45,
    DEBTORS_LIST: 309,
    GST_APPLIED: 313,
    LETTER_OF_INTENT: 316,
    RELEVANT_LICENSE: 48,
    SALES_TAX: 50,
    LATEST_TAX: 51,
    ENCUMBRANCE: 52,
    COPIES_TRUST_DEEDS: 53,
    MARKET_SURVEY_REPORT: 54,
    CONTINGENT_LIABILITIES: 324,

    FIELD_AUDIT_REPORT: 502,
    BANK_STATEMENT_OF_12_MONTHS: 506,
    FINANCIAL_FIGURE: 510,
    CENTRAL_TAX_REGISTRATION: 514,
    CENTRAL_EXCISE_RESGISTRATION: 518,
    VAT_REGISTRATION: 522,
    LIST_OF_DIRECTORS: 526,

    CASH_CHEQUE_RECEIPT: 352,
    TL_PROFILE_PIC_COMPANY: 536,
    TL_SITE_OR_PROMOTERS_PHOTOS: 540,
    BROCHURE_OF_PROPOSED_ACTIVITY: 551,
    AADHAR_CARD: 552
  },
  ProductDocumentMapping_USL: {
    PROFILE_PIC: 274,
    COAPP_PROFILE_PIC: 275,
    COAPP_COPY_OF_PAN_CARD: 292,
    BROCHURE_OF_PROPOSED_ACTIVITIES: 281,
    CERTIFICATE_OF_INCORPORATION: 282,
    COPY_OF_PAN_CARD: 283,
    LAST_AUDITED_ANNUAL_REPORT: 276,
    SANCTION_LETTER_COPY: 277,
    LAST_IT_RETURN: 278,
    NETWORTH_STATEMENT_OF_DIRECTORS: 279,
    PROVISIONAL_FINANCIALS: 280,
    PAN_OF_DIRECTORS: 284,
    DETAILED_LIST_OF_SHAREHOLDERS: 285,
    PHOTO_OF_DIRECTORS: 286,
    CMA: 327,
    COMPANYS_ACT_CMA: 328,

    COAPP_STATEMENT_OF_BANK_ACC: 287,
    COAPP_AUDITED_UNAUD_BAL_SHEET: 290,
    COAPP_ADDRESS_PROOF: 291,
    COAPP_ITR_ONLY: 288,
    COAPP_FORM_16: 289,
    COAPP_COPY_OF_AADHAR_CARD: 293,
    BANK_STATEMENT: 296,
    IT_RETURN_DIRECTOR: 299,
    FINANCIALS_OF_SUBSIDIARIES: 300,
    ASSESSMENT_ORDERS: 301,
    DIRECTOR_ADDRESS: 304,
    DIRECTOR_RESOLUTION: 307,

    MOM_AOA: 311,
    DEBTORS_LIST: 310,
    GST_APPLIED: 314,
    LETTER_OF_INTENT: 317,
    RELEVANT_LICENSE: 318,
    SALES_TAX: 319,
    LATEST_TAX: 326,
    ENCUMBRANCE: 320,
    COPIES_TRUST_DEEDS: 321,
    MARKET_SURVEY_REPORT: 322,
    CONTINGENT_LIABILITIES: 325,

    FIELD_AUDIT_REPORT: 503,
    BANK_STATEMENT_OF_12_MONTHS: 507,
    FINANCIAL_FIGURE: 511,
    CENTRAL_TAX_REGISTRATION: 515,
    CENTRAL_EXCISE_RESGISTRATION: 519,
    VAT_REGISTRATION: 523,
    LIST_OF_DIRECTORS: 527,

    CASH_CHEQUE_RECEIPT: 353,
    USL_PROFILE_PIC_COMPANY: 537,
    USL_SITE_OR_PROMOTERS_PHOTOS: 541
  },
  ProductDocumentMapping_WCTL: {
    PROFILE_PIC: 394,

    BROCHURE_OF_PROPOSED_ACTIVITIES: 367,
    CERTIFICATE_OF_INCORPORATION: 368,
    COPY_OF_PAN_CARD: 369,
    LAST_AUDITED_ANNUAL_REPORT: 375,
    SANCTION_LETTER_COPY: 376,
    LAST_IT_RETURN: 377,
    NETWORTH_STATEMENT_OF_DIRECTORS: 378,
    PROVISIONAL_FINANCIALS: 379,
    PAN_OF_DIRECTORS: 380,
    DETAILED_LIST_OF_SHAREHOLDERS: 381,
    PHOTO_OF_DIRECTORS: 382,
    CMA: 373,
    COMPANYS_ACT_CMA: 374,

    BANK_STATEMENT: 395,
    IT_RETURN_DIRECTOR: 396,
    FINANCIALS_OF_SUBSIDIARIES: 386,
    ASSESSMENT_ORDERS: 388,
    DIRECTOR_ADDRESS: 397,
    DIRECTOR_RESOLUTION: 398,

    MOM_AOA: 384,
    DEBTORS_LIST: 399,
    GST_APPLIED: 400,
    LETTER_OF_INTENT: 401,
    RELEVANT_LICENSE: 387,
    SALES_TAX: 389,
    LATEST_TAX: 390,
    ENCUMBRANCE: 391,
    COPIES_TRUST_DEEDS: 392,
    MARKET_SURVEY_REPORT: 393,
    CONTINGENT_LIABILITIES: 402,

    FIELD_AUDIT_REPORT: 504,
    BANK_STATEMENT_OF_12_MONTHS: 508,
    FINANCIAL_FIGURE: 512,
    CENTRAL_TAX_REGISTRATION: 516,
    CENTRAL_EXCISE_RESGISTRATION: 520,
    VAT_REGISTRATION: 524,
    LIST_OF_DIRECTORS: 528,
    WCTL_PROFILE_PIC_COMPANY: 538,
    WCTL_SITE_OR_PROMOTERS_PHOTOS: 542



  },
  ProductDocumentMapping_HL: {
    PROFILE_PIC: 228,
    COAPP_PROFILE_PIC: 229,
    GUARANTOR_PROFILE_PIC: 230,
    COPY_OF_PAN_CARD: 55,
    COPY_OF_AADHAR_CARD: 56,
    COAPP_COPY_OF_PAN_CARD: 57,
    COAPP_COPY_OF_AADHAR_CARD: 58,
    GUARANTOR_COPY_OF_PAN_CARD: 59,
    GUARANTOR_COPY_OF_AADHAR_CARD: 60,

    STATEMENT_OF_BANK_ACC: 61,
    INCOME_PROOF_LATEST_SALARY: 62,
    INCOME_TAX_RETURNS: 63,
    AUDITED_UNAUD_BAL_SHEET: 64,
    ADDRESS_PROOF: 65,
    INCOME_PROOF_OF_ENTITY: 66,
    CROP_CULTIVATION: 67,
    DOC_PROOF_OF_ALLIED_ACT: 68,
    ITR_ONLY: 243,
    FORM_16: 248,

    COAPP_STATEMENT_OF_BANK_ACC: 69,
    COAPP_INCOME_PROOF_LATEST_SALARY: 70,
    COAPP_INCOME_TAX_RETURNS: 71,
    COAPP_AUDITED_UNAUD_BAL_SHEET: 72,
    COAPP_ADDRESS_PROOF: 73,
    COAPP_INCOME_PROOF_OF_ENTITY: 74,
    COAPP_CROP_CULTIVATION: 75,
    COAPP_DOC_PROOF_OF_ALLIED_ACT: 76,
    COAPP_ITR_ONLY: 254,
    COAPP_FORM_16: 259,

    GUARANTOR_STATEMENT_OF_BANK_ACC: 77,
    GUARANTOR_INCOME_PROOF_LATEST_SALARY: 78,
    GUARANTOR_INCOME_TAX_RETURNS: 79,
    GUARANTOR_AUDITED_UNAUD_BAL_SHEET: 80,
    GUARANTOR_ADDRESS_PROOF: 81,
    GUARANTOR_INCOME_PROOF_OF_ENTITY: 82,
    GUARANTOR_CROP_CULTIVATION: 83,
    GUARANTOR_DOC_PROOF_OF_ALLIED_ACT: 84,
    GUARANTOR_ITR_ONLY: 264,
    GUARANTOR_FORM_16: 269
  },
  ProductDocumentMapping_CL: {
    PROFILE_PIC: 231,
    COAPP_PROFILE_PIC: 232,
    GUARANTOR_PROFILE_PIC: 233,
    COPY_OF_PAN_CARD: 99,
    COPY_OF_AADHAR_CARD: 100,
    COAPP_COPY_OF_PAN_CARD: 101,
    COAPP_COPY_OF_AADHAR_CARD: 102,
    GUARANTOR_COPY_OF_PAN_CARD: 103,
    GUARANTOR_COPY_OF_AADHAR_CARD: 104,

    STATEMENT_OF_BANK_ACC: 105,
    INCOME_PROOF_LATEST_SALARY: 106,
    INCOME_TAX_RETURNS: 107,
    AUDITED_UNAUD_BAL_SHEET: 108,
    ADDRESS_PROOF: 109,
    INCOME_PROOF_OF_ENTITY: 110,
    CROP_CULTIVATION: 111,
    DOC_PROOF_OF_ALLIED_ACT: 112,
    ITR_ONLY: 244,
    FORM_16: 249,

    COAPP_STATEMENT_OF_BANK_ACC: 113,
    COAPP_INCOME_PROOF_LATEST_SALARY: 114,
    COAPP_INCOME_TAX_RETURNS: 115,
    COAPP_AUDITED_UNAUD_BAL_SHEET: 116,
    COAPP_ADDRESS_PROOF: 117,
    COAPP_INCOME_PROOF_OF_ENTITY: 118,
    COAPP_CROP_CULTIVATION: 119,
    COAPP_DOC_PROOF_OF_ALLIED_ACT: 120,
    COAPP_ITR_ONLY: 255,
    COAPP_FORM_16: 260,

    GUARANTOR_STATEMENT_OF_BANK_ACC: 121,
    GUARANTOR_INCOME_PROOF_LATEST_SALARY: 122,
    GUARANTOR_INCOME_TAX_RETURNS: 123,
    GUARANTOR_AUDITED_UNAUD_BAL_SHEET: 124,
    GUARANTOR_ADDRESS_PROOF: 125,
    GUARANTOR_INCOME_PROOF_OF_ENTITY: 126,
    GUARANTOR_CROP_CULTIVATION: 127,
    GUARANTOR_DOC_PROOF_OF_ALLIED_ACT: 128,
    GUARANTOR_ITR_ONLY: 265,
    GUARANTOR_FORM_16: 270
  },
  ProductDocumentMapping_PL: {
    PROFILE_PIC: 234,
    COAPP_PROFILE_PIC: 235,
    GUARANTOR_PROFILE_PIC: 236,
    COPY_OF_PAN_CARD: 136,
    COPY_OF_AADHAR_CARD: 137,
    COAPP_COPY_OF_PAN_CARD: 138,
    COAPP_COPY_OF_AADHAR_CARD: 139,
    GUARANTOR_COPY_OF_PAN_CARD: 140,
    GUARANTOR_COPY_OF_AADHAR_CARD: 141,

    STATEMENT_OF_BANK_ACC: 142,
    INCOME_PROOF_LATEST_SALARY: 143,
    INCOME_TAX_RETURNS: 144,
    AUDITED_UNAUD_BAL_SHEET: 145,
    ADDRESS_PROOF: 146,
    INCOME_PROOF_OF_ENTITY: 147,
    CROP_CULTIVATION: 148,
    DOC_PROOF_OF_ALLIED_ACT: 149,
    ITR_ONLY: 245,
    FORM_16: 250,

    COAPP_STATEMENT_OF_BANK_ACC: 150,
    COAPP_INCOME_PROOF_LATEST_SALARY: 151,
    COAPP_INCOME_TAX_RETURNS: 152,
    COAPP_AUDITED_UNAUD_BAL_SHEET: 153,
    COAPP_ADDRESS_PROOF: 154,
    COAPP_INCOME_PROOF_OF_ENTITY: 155,
    COAPP_CROP_CULTIVATION: 156,
    COAPP_DOC_PROOF_OF_ALLIED_ACT: 157,
    COAPP_ITR_ONLY: 256,
    COAPP_FORM_16: 261,

    GUARANTOR_STATEMENT_OF_BANK_ACC: 158,
    GUARANTOR_INCOME_PROOF_LATEST_SALARY: 159,
    GUARANTOR_INCOME_TAX_RETURNS: 160,
    GUARANTOR_AUDITED_UNAUD_BAL_SHEET: 161,
    GUARANTOR_ADDRESS_PROOF: 162,
    GUARANTOR_INCOME_PROOF_OF_ENTITY: 163,
    GUARANTOR_CROP_CULTIVATION: 164,
    GUARANTOR_DOC_PROOF_OF_ALLIED_ACT: 165,
    GUARANTOR_ITR_ONLY: 266,
    GUARANTOR_FORM_16: 271
  },
  ProductDocumentMapping_LAP: {
    PROFILE_PIC: 237,
    COAPP_PROFILE_PIC: 238,
    GUARANTOR_PROFILE_PIC: 239,
    COPY_OF_PAN_CARD: 166,
    COPY_OF_AADHAR_CARD: 167,
    COAPP_COPY_OF_PAN_CARD: 168,
    COAPP_COPY_OF_AADHAR_CARD: 169,
    GUARANTOR_COPY_OF_PAN_CARD: 170,
    GUARANTOR_COPY_OF_AADHAR_CARD: 171,

    STATEMENT_OF_BANK_ACC: 172,
    INCOME_PROOF_LATEST_SALARY: 173,
    INCOME_TAX_RETURNS: 174,
    AUDITED_UNAUD_BAL_SHEET: 175,
    ADDRESS_PROOF: 176,
    INCOME_PROOF_OF_ENTITY: 177,
    CROP_CULTIVATION: 178,
    DOC_PROOF_OF_ALLIED_ACT: 179,
    ITR_ONLY: 246,
    FORM_16: 251,

    COAPP_STATEMENT_OF_BANK_ACC: 180,
    COAPP_INCOME_PROOF_LATEST_SALARY: 181,
    COAPP_INCOME_TAX_RETURNS: 182,
    COAPP_AUDITED_UNAUD_BAL_SHEET: 183,
    COAPP_ADDRESS_PROOF: 184,
    COAPP_INCOME_PROOF_OF_ENTITY: 185,
    COAPP_CROP_CULTIVATION: 186,
    COAPP_DOC_PROOF_OF_ALLIED_ACT: 187,
    COAPP_ITR_ONLY: 257,
    COAPP_FORM_16: 262,

    GUARANTOR_STATEMENT_OF_BANK_ACC: 188,
    GUARANTOR_INCOME_PROOF_LATEST_SALARY: 189,
    GUARANTOR_INCOME_TAX_RETURNS: 190,
    GUARANTOR_AUDITED_UNAUD_BAL_SHEET: 191,
    GUARANTOR_ADDRESS_PROOF: 192,
    GUARANTOR_INCOME_PROOF_OF_ENTITY: 193,
    GUARANTOR_CROP_CULTIVATION: 194,
    GUARANTOR_DOC_PROOF_OF_ALLIED_ACT: 195,
    GUARANTOR_ITR_ONLY: 267,
    GUARANTOR_FORM_16: 272
  },
  ProductDocumentMapping_LAS: {
    PROFILE_PIC: 240,
    COAPP_PROFILE_PIC: 241,
    GUARANTOR_PROFILE_PIC: 242,
    COPY_OF_PAN_CARD: 196,
    COPY_OF_AADHAR_CARD: 197,
    COAPP_COPY_OF_PAN_CARD: 198,
    COAPP_COPY_OF_AADHAR_CARD: 199,
    GUARANTOR_COPY_OF_PAN_CARD: 200,
    GUARANTOR_COPY_OF_AADHAR_CARD: 201,

    STATEMENT_OF_BANK_ACC: 202,
    INCOME_PROOF_LATEST_SALARY: 203,
    INCOME_TAX_RETURNS: 204,
    AUDITED_UNAUD_BAL_SHEET: 205,
    ADDRESS_PROOF: 206,
    INCOME_PROOF_OF_ENTITY: 207,
    CROP_CULTIVATION: 208,
    DOC_PROOF_OF_ALLIED_ACT: 209,
    ITR_ONLY: 247,
    FORM_16: 252,

    COAPP_STATEMENT_OF_BANK_ACC: 210,
    COAPP_INCOME_PROOF_LATEST_SALARY: 211,
    COAPP_INCOME_TAX_RETURNS: 212,
    COAPP_AUDITED_UNAUD_BAL_SHEET: 213,
    COAPP_ADDRESS_PROOF: 214,
    COAPP_INCOME_PROOF_OF_ENTITY: 215,
    COAPP_CROP_CULTIVATION: 216,
    COAPP_DOC_PROOF_OF_ALLIED_ACT: 217,
    COAPP_ITR_ONLY: 258,
    COAPP_FORM_16: 263,

    GUARANTOR_STATEMENT_OF_BANK_ACC: 218,
    GUARANTOR_INCOME_PROOF_LATEST_SALARY: 219,
    GUARANTOR_INCOME_TAX_RETURNS: 220,
    GUARANTOR_AUDITED_UNAUD_BAL_SHEET: 221,
    GUARANTOR_ADDRESS_PROOF: 222,
    GUARANTOR_INCOME_PROOF_OF_ENTITY: 223,
    GUARANTOR_CROP_CULTIVATION: 224,
    GUARANTOR_DOC_PROOF_OF_ALLIED_ACT: 225,
    GUARANTOR_ITR_ONLY: 268,
    GUARANTOR_FORM_16: 273
  },
  ProductDocumentMapping_SP: {
    PROFILE_PIC_SP: 2,
    BROCHURE_OF_ORGANIZATION: 3,
    COPY_OF_PAN_CARD: 4,
  },
  ProductDocumentMapping_NP: {
    PROFILE_PIC_NP: 6,
  },
  NatureOfOccupation: {
    SAL: "Salaried",
    BUS: "Business",
    SELF_EMP: "Self Employed",
    SELF_EMP_PROF: "Self Employed Professional",
    AGR: "Agriculturist",
    PENS: "Pensioner"
  },

  LoanType: {
    Corporate: {
      CORPORATE_TYPE: "cr",
      Debt: {
        DEBT_TYPE: "dt",
        WORKING_CAPITAL: "wc",
        TERM_LOAN: "tl",
        UNSECURED_LOAN: "usl",
        WC_TL_LOAN: "wctl"
      }
    },
    Retail: {
      RETAIL_TYPE: "rt",
      HOME_LOAN: "hl",
      AUTO_LOAN: "al",
      EDUCATION_LOAN: "el",
      PERSONAL_LOAN: "pl",
      LOAN_AGAINST_PROPERTY: "lap",
      LOAN_AGAINST_SHARES: "las"
    },
    MFI: {
      MFI_TYPE: "MFI"
    }
  },
  ProductList: [
    {
      id: 1,
      name: "Working Capital",
      code: "wc",
    },
    {
      id: 2,
      name: "Term Loan",
      code: "tl",
    },
    {
      id: 3,
      name: "Home Loan",
      code: "hl",
    },
    {
      id: 7,
      name: "Personal Loan",
      code: "pl",
    },
    {
      id: 12,
      name: "Auto Loan",
      code: "al",
    },
    {
      id: 13,
      name: "Loan Against Property",
      code: "lap",
    },
    {
      id: 14,
      name: "Loan Against Shares",
      code: "las",
    },
    {
      id: 15,
      name: "Unsecured Loan",
      code: "usl",
    },
    {
      id: 16,
      name: "Working Capital Term Loan",
      code: "wctl",
    },
    {
      id: 17,
      name: "Micro Finance Institute Loan",
      code: "mfi",
    }

  ],
  Product: {
    WORKING_CAPITAL: {
      id: 1,
      name: "Working Capital",
      code: "wc",
    },
    TERM_LOAN: {
      id: 2,
      name: "Term Loan",
      code: "tl",
    },
    HOME_LOAN: {
      id: 3,
      name: "Home Loan",
      code: "hl",
    },
    PERSONAL_LOAN: {
      id: 7,
      name: "Personal Loan",
      code: "pl",
    },
    AUTO_LOAN: {
      id: 12,
      name: "Auto Loan",
      code: "al",
    },
    LAP_LOAN: {
      id: 13,
      name: "Loan Against Property",
      code: "lap",
    },
    LAS_LOAN: {
      id: 14,
      name: "Loan Against Shares",
      code: "las",
    }
    ,
    UNSECURED_LOAN: {
      id: 15,
      name: "Unsecured Loan",
      code: "usl",
    },
    WC_TL_LOAN: {
      id: 16,
      name: "Working Capital Term Loan",
      code: "wctl",
    },
    MFI: {
      id: 17,
      name: "Micro Finance Institute Loan",
      code: "mfi",
    },
    MUDRA_LOAN: {
      id: 10,
      name: "Mudra Loan",
      code: "ml",
    }

  },

  ProposalStatus: {
    PENDING: {
      id: 1,
      name: "Pending",
      code: "pen",
    },
    SANCTION: {
      id: 2,
      name: "Sanction",
      code: "san",
    },
    DISBURSE: {
      id: 3,
      name: "Disburse",
      code: "dis",
    }

  },


  UserMainType: {
    RETAIL: 1,
    CORPORATE: 2
  },
  ErrorMessage: {
    SOMETHING_WENT_WRONG: "Something went wrong !",
    INVALID_REQUEST: "Invalid Request."
  },
  Broadcast_Frames_Events: {
    wc: {
      CR_ACHIEVEMENTS: "cr_wc_achievements",
      CR_EXISTING_PRODUCTS: "cr_wc_existing_products",
      CR_PROMOTORS_BACKGOURND: "cr_wc_promotors_background",
      CR_DIRECTORS_BACKGOURND: "cr_wc_directors_background",
      CR_PROMOTORS_OWNERSHIP: "cr_wc_promotors_ownership",
      CR_PAST_FINANCIAL: "cr_wc_past_financial",
      CR_FUTURE_PROJECTION: "cr_wc_future_projection",
      CR_CURRENT_FINANCIAL_ARRANGEMENT: "cr_wc_current_financial_arrangement",
      CR_CREADIT_RATING: "cr_wc_credit_rating",
      CR_COLLATERAL_SECURITY: "cr_wc_collateral_Security",
      CR_MONTHLY_TURNOVER: "cr_monthly_turnover",
      CR_DETAILS_OF_GUARANTORS: "cr_details_of_guarantors",
      CR_ASSOCIATED_CONCERN: "cr_associated_concern",
      CR_REFERENCE: "cr_wc_reference",
      CR_PROPOSED_PRODUCTS_NTB: "cr_wc_proposed_product_ntb",
      CR_DETAILS_OF_GUARANTORS_NTB: "cr_details_of_guarantors_ntb",
      CR_DISBURSEMENT_REQUEST: "disbursement_details"
    },
    tl: {
      CR_ACHIEVEMENTS: "cr_tl_achievements",
      CR_EXISTING_PRODUCTS: "cr_tl_existing_products",
      CR_PROMOTORS_BACKGOURND: "cr_tl_promotors_background",
      CR_DIRECTORS_BACKGOURND: "cr_tl_directors_background",
      CR_PROMOTORS_OWNERSHIP: "cr_tl_promotors_ownership",
      CR_PAST_FINANCIAL: "cr_tl_past_financial",
      CR_FUTURE_PROJECTION: "cr_tl_future_projection",
      CR_CURRENT_FINANCIAL_ARRANGEMENT: "cr_tl_current_financial_arrangement",
      CR_CREADIT_RATING: "cr_tl_credit_rating",
      CR_COLLATERAL_SECURITY: "cr_tl_collateral_Security",
      CR_COST_OF_ESTIMATE: "cr_tl_cost_of_estimate",
      CR_MEANS_OF_FINANCE: "cr_tl_means_of_finance",
      CR_DETAILS_OF_GUARANTORS: "cr_details_of_guarantors",
      CR_ASSOCIATED_CONCERN: "cr_associated_concern",
      CR_REFERENCE: "cr_tl_reference",
      CR_PROPOSED_PRODUCTS_NTB: "cr_tl_proposed_product_ntb",
      CR_DETAILS_OF_GUARANTORS_NTB: "cr_details_of_guarantors_ntb"
    },
    usl: {
      CR_ACHIEVEMENTS: "cr_usl_achievements",
      CR_EXISTING_PRODUCTS: "cr_usl_existing_products",
      CR_PROMOTORS_BACKGOURND: "cr_usl_promotors_background",
      CR_DIRECTORS_BACKGOURND: "cr_usl_directors_background",
      CR_PROMOTORS_OWNERSHIP: "cr_usl_promotors_ownership",
      CR_PAST_FINANCIAL: "cr_usl_past_financial",
      CR_FUTURE_PROJECTION: "cr_usl_future_projection",
      CR_CURRENT_FINANCIAL_ARRANGEMENT: "cr_usl_current_financial_arrangement",
      CR_CREADIT_RATING: "cr_usl_credit_rating",
      CR_COLLATERAL_SECURITY: "cr_usl_collateral_Security",
      CR_COST_OF_ESTIMATE: "cr_usl_cost_of_estimate",
      CR_MEANS_OF_FINANCE: "cr_usl_means_of_finance",
      CR_DETAILS_OF_GUARANTORS: "cr_details_of_guarantors",
      CR_ASSOCIATED_CONCERN: "cr_associated_concern",
      CR_BANKACC_HELD: "cr_usl_bankacc_held",
      CR_CREDITCARD: "cr_usl_creditcard",
      CR_REFERENCE: "cr_usl_reference",
      CR_DETAILS_OF_GUARANTORS_NTB: "cr_details_of_guarantors_ntb"
    },
    wctl: {
      CR_ACHIEVEMENTS: "cr_wctl_achievements",
      CR_EXISTING_PRODUCTS: "cr_wctl_existing_products",
      CR_PROMOTORS_BACKGOURND: "cr_wctl_promotors_background",
      CR_DIRECTORS_BACKGOURND: "cr_wctl_directors_background",
      CR_PROMOTORS_OWNERSHIP: "cr_wctl_promotors_ownership",
      CR_PAST_FINANCIAL: "cr_wctl_past_financial",
      CR_FUTURE_PROJECTION: "cr_wctl_future_projection",
      CR_CURRENT_FINANCIAL_ARRANGEMENT: "cr_wctl_current_financial_arrangement",
      CR_CREADIT_RATING: "cr_wctl_credit_rating",
      CR_COLLATERAL_SECURITY: "cr_wctl_collateral_Security",
      CR_COST_OF_ESTIMATE: "cr_wctl_cost_of_estimate",
      CR_MEANS_OF_FINANCE: "cr_wctl_means_of_finance",
      CR_DETAILS_OF_GUARANTORS: "cr_wctl_details_of_guarantors",
      CR_ASSOCIATED_CONCERN: "cr_wctl_associated_concern",
      CR_BANKACC_HELD: "cr_wctl_bankacc_held",
      CR_CREDITCARD: "cr_wctl_creditcard",
      CR_REFERENCE: "cr_wctl_reference",
      CR_PROPOSED_PRODUCTS_NTB: "cr_wctl_proposed_product_ntb",
      CR_DETAILS_OF_GUARANTORS_NTB: "cr_details_of_guarantors_ntb"
    },
    hl: {
      RT_BANKACC_HELD: "rt_hl_bankacc_held",
      RT_CREDITCARD: "rt_hl_creditcard",
      RT_EXISTING_LOAN: "rt_hl_existing_loan",
      RT_FIXED_DEPOSIT: "rt_hl_fixed_deposit",
      RT_OTHER_CURRENT_ASSET: "rt_hl_other_current_asset",
      RT_OTHER_INCOME_DETAIL: "rt_hl_other_income_detail",
      RT_REFERENCE: "rt_hl_reference",
      RT_SECURITY_DETAIL: "rt_hl_security_detail",
      RT_OTHER_PROPERTY_DETAIL: "rt_hl_other_property_detail",
      RT_PURCHASE_PROPERTY_DETAIL: "rt_hl_purchase_property_detail",
      RT_EMP_FIN_DETAIL: "rt_hl_emp_fin_detail",
      APF_EXCEL_UPLOAD: "apf_excel_upload"
    },
    cl: {
      RT_BANKACC_HELD: "rt_cl_bankacc_held",
      RT_CREDITCARD: "rt_cl_creditcard",
      RT_EXISTING_LOAN: "rt_cl_existing_loan",
      RT_FIXED_DEPOSIT: "rt_cl_fixed_deposit",
      RT_OTHER_CURRENT_ASSET: "rt_cl_other_current_asset",
      RT_OTHER_INCOME_DETAIL: "rt_cl_other_income_detail",
      RT_REFERENCE: "rt_cl_reference",
      RT_SECURITY_DETAIL: "rt_cl_security_detail"
    },
    pl: {
      RT_BANKACC_HELD: "rt_pl_bankacc_held",
      RT_CREDITCARD: "rt_pl_creditcard",
      RT_EXISTING_LOAN: "rt_pl_existing_loan",
      RT_FIXED_DEPOSIT: "rt_pl_fixed_deposit",
      RT_OTHER_CURRENT_ASSET: "rt_pl_other_current_asset",
      RT_OTHER_INCOME_DETAIL: "rt_pl_other_income_detail",
      RT_REFERENCE: "rt_pl_reference",
      RT_SECURITY_DETAIL: "rt_pl_security_detail",
      RT_OBLIGATION_DETAIL: "rt_pl_obligation_detail",
      RT_INCOME_DETAIL_FINAL: "rt_pl_income_detail_final",
      RT_INCOME_DETAIL_PROFILE: "rt_pl_income_detail_profile",
    },
    lap: {
      RT_BANKACC_HELD: "rt_lap_bankacc_held",
      RT_CREDITCARD: "rt_lap_creditcard",
      RT_EXISTING_LOAN: "rt_lap_existing_loan",
      RT_FIXED_DEPOSIT: "rt_lap_fixed_deposit",
      RT_OTHER_CURRENT_ASSET: "rt_lap_other_current_asset",
      RT_OTHER_INCOME_DETAIL: "rt_lap_other_income_detail",
      RT_REFERENCE: "rt_lap_reference",
      RT_SECURITY_DETAIL: "rt_lap_security_detail"
    },
    las: {
      RT_BANKACC_HELD: "rt_las_bankacc_held",
      RT_CREDITCARD: "rt_las_creditcard",
      RT_EXISTING_LOAN: "rt_las_existing_loan",
      RT_FIXED_DEPOSIT: "rt_las_fixed_deposit",
      RT_OTHER_CURRENT_ASSET: "rt_las_other_current_asset",
      RT_OTHER_INCOME_DETAIL: "rt_las_other_income_detail",
      RT_REFERENCE: "rt_las_reference",
      RT_SECURITY_DETAIL: "rt_las_security_detail"
    },
    other: {
      LAT_LON: "lat_lon",
      MFI_REMARK: "mfi_remark"
    }
  },
  Broadcast_SP_Functions: {
    SP: {
      CLIENT_COUNT_LISTING: "client_count_list",
      FS_FP_LISTINGS: "fs_fp_listing",
    },
  },
  TabType: {
    PROFILE: 1,
    PROFILE_CO_APPLICANT: 2,
    PROFILE_GUARANTOR: 3,
    PRIMARY_INFORMATION: 4,
    PRIMARY_UPLOAD: 5,
    FINAL_UPLOAD: 6,
    FINAL_DPR_UPLOAD: 7,
    FINAL_CO_APPLICANT: 8,
    FINAL_GUARANTOR: 9,
    FINAL_MCQ: 10,
    FINAL_INFORMATION: 11,
    CONNECTIONS: 12,
    MATCHES: 13,
  },



  PopupUrl: {
    confirmation: "app/common-utils/popup/htmls/confirmationPopup.html",
    cashPaymentPopup: "app/fund-seeker/corporate/htmls/one-form/CashPaymentPopup.html|cashPopupCtrl",
    chequePaymentPopup: "app/fund-seeker/corporate/htmls/one-form/ChequePaymentPopup.html|chequePopupCtrl",
    validateCashPaymentPopup: "app/fund-seeker/corporate/htmls/one-form/ValidateCashPayment.html|validateCashPaymentCtrl",
    validateChequePaymentPopup: "app/fund-seeker/corporate/htmls/one-form/ValidateChequePayment.html|validateChequePaymentCtrl",
    yesNoPopup: "app/common-utils/popup/htmls/yesNoPopup.html",
    emailVerifyPopup: "app/common-utils/popup/htmls/emailVerifyPopup.html",
    matchesPopup: "app/fund-seeker/popup/htmls/matchesPopup.html|matchesPopupCtrl",
    mapPopup: "app/common-pages/googleMap.html|googleMapCtrl",
    addNewProductPopup: "app/fund-provider/htmls/pop-up/add-new-loan-popup.html|addNewLoanPopupCtrl",
    mudraAddNewProductPopup: "app/fund-provider/htmls/pop-up/mudra-add-new-loan-popup.html|mudraAddNewLoanPopupCtrl",
    odopAddNewProductPopup: "app/fund-provider/htmls/pop-up/odop-add-new-loan-popup.html|odopAddNewLoanPopupCtrl",
    addCustomerNbfcPopup: "app/fund-provider/htmls/pop-up/addCustomerNbfc.html|addCustomerNbfcCtrl",
    selectCheckerPopup: "app/fund-seeker/popup/htmls/selectCheckerPopup.html|selectCheckerPopupCtrl",
    addDisbursementDetailPopup: "app/fund-provider/htmls/pop-up/add-loan-disbursement-details.html|addDisbursementDetailCtrl",
    saveParameterPopup: "app/fund-provider/htmls/pop-up/fpMatchesPopup.html|saveParameterPopupCtrl",
    npPopup: "app/network-partner/htmls/npPopup.html|npPopupCtrl",
    paymentPopup: "app/fund-seeker/corporate/htmls/one-form/paymentForm.html|paymentPopupCtrl",
    copyLoanPopup: "app/fund-seeker/popup/htmls/copyLoanPopup.html|copyLoanPopupCtrl",
    approvalAfterSanctionPopup: "app/fund-provider/htmls/pop-up/approval-after-sanction-popup.html|approvalAfterSanctionPopupCtrl",
    scoringPopup: "app/fund-provider/htmls/pop-up/scoringPopup.html|scoringPopupCtrl",
    scoringDfsPopup: "app/fund-provider/htmls/pop-up/scoringDfsPopup.html|scoringDfsPopupCtrl",
    scoringVfsPopup: "app/fund-provider/htmls/pop-up/scoringVfsPopup.html|scoringVfsPopupCtrl",
    loanPurposePopup: "app/fund-provider/htmls/pop-up/loanPurposePopup.html|loanPurposePopupCtrl",
    customerInput: "app/fund-seeker/popup/htmls/customerInput.html|customerInputCtrl",
    offlineSanction: "app/fund-provider/htmls/pop-up/offlineSanctionPopup.html|offlineSanctionPopupCtrl",
    offlineDisbursement: "app/fund-provider/htmls/pop-up/offlineDisbursementPopup.html|offlineDisburmentPopupCtrl",
    disbursementHistory: "app/fund-provider/htmls/pop-up/disbursmentHistoryPopup.html|offlineDisburmentPopupCtrl",
    reopenapplication: "app/fund-provider/htmls/pop-up/re-openpopup.html|reOpenPopupCtrl",
    dropdownPopup: "app/fund-provider/htmls/pop-up/dropdownPropup.html|dropdownPropupCtrl",
    offlineProposalRejectPopup: "app/fund-provider/htmls/pop-up/offlineProposalRejectPopup.html|offlineProposalRejectPopupCtrl",
    offlineSanctionRejectPopup: "app/fund-provider/htmls/pop-up/offlineSanctionRejectPopup.html|offlineSanctionRejectPopupCtrl",
    uniformProductActionComment: "app/fund-provider/htmls/pop-up/uniformProductActionComment.html|uniformProductActionCommentCtrl",
    newAssignBranchVerifyPopup: "app/fund-seeker/popup/htmls/new_assign_branch_verify_popup.html|newAssignBranchVerifyPopupCtrl",
    offlineProposalTransferPopup: "app/fund-provider/htmls/pop-up/offlineProposalTransferPopup.html|offlineProposalTransferPopupCtrl",
    updateForceFullyPassPopup: "app/common-pages/updateForceFullyPassPopup.html|updateForceFullyPassPopupCtrl",
    OTPPopup: "app/common-pages/OTPPopup.html|OTPPopupCtrl",
    projectDetailsPopup: "app/fund-provider/htmls/pop-up/project-details-popup.html|projectDetailsPopupCtrl",
    projectPhotosPopup: "app/fund-provider/htmls/pop-up/projectPhotosPopup.html|projectPhotosPopupCtrl",
    apfFileUploadPopup: "app/fund-provider/htmls/pop-up/apfFileUploadPopup.html|apfFileUploadPopupCtrl",
    loanAmtConfirmationPopup: "app/fund-provider/htmls/pop-up/loanAmtConfirmation.html|loanAmtConfirmationCtrl",
    remarkConfirmationPopup: "app/fund-provider/htmls/pop-up/remarkConfirmation.html|remarkConfirmationCtrl",
    reasonForCoLendingRatioSendBackPopup: "app/fund-provider/htmls/pop-up/reason-for-ratio-sendback-popup.html|reasonForCoLendingRatioSendBackCtrl",
    reasonForServiceFeesSendBackPopup: "app/fund-provider/htmls/pop-up/reason-for-service-fees-sendback-popup.html|reasonForServiceFeesSendBackCtrl",
    fileUploadPopup: "app/fund-seeker/popup/htmls/fileUploadPopup.html|fileUploadPopupCtrl",
    requestForDisbursementPopup: "app/fund-provider/htmls/pop-up/request-for-disbursement.html|requestForDisbursementCtrl",
    //fileUploadPopup : "app/fund-seeker/popup/htmls/fileUploadPopup.html|fileUploadPopupCtrl",
    nbfcNewSanctionPopup: "app/fund-provider/htmls/pop-up/nbfcNewSanction.html|nbfcNewSanctionCtrl",
    handsOffPopup: "app/fund-provider/htmls/pop-up/disbursementHandof.html|disbursementHandofCtrl",
    nbfcCollectionRejectPopup: "app/fund-seeker/popup/htmls/nbfcCollectionRejectPopup.html|nbfcCollectionRejectPopCtrl",
    demandAdviceRejectPopup: "app/fund-seeker/popup/htmls/demandAdviceRejectPopup.html|demandAdviceRejectPopCtrl",
    teaserPermissionConfirmationPopup: "app/common-pages/teaserPermissionConfirmation.html",
    disburseConfirmationPopup: "app/fund-provider/htmls/pop-up/openDisburseConfirmationPopup.html|disburseConfirmationPopCtrl",
    manuallyDisbursePopup: "app/fund-provider/htmls/pop-up/manuallyDisbursePopup.html|manuallyDisbursePopCtrl",
    scoringEretailPopup: "app/fund-provider/htmls/pop-up/scoringEretailPopup.html|scoringEretailPopupCtrl",
    subLoanTypeSelectionPopup: "app/fund-provider/htmls/pop-up/subLoanTypeSelectionPopup.html|subLoanTypeSelectionPopupCtrl"
  }, FileType: {
    jpg: "image/jpg",
    jpeg: "image/jpeg",
    png: "image/png",
    pdf: "application/pdf",
    xls: "application/vnd.ms-excel",
    xlsx: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    doc: "application/msword",
    docx: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    ppt: "application/vnd.ms-powerpointtd>",
    pptx: "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    zip: "application/x-zip-compressed",
  }, Roles: {
    MAKER: {
      id: 10,
      value: "Maker"
    },
    CHECKER: {
      id: 11,
      value: "Checker"
    }
  },

  SchemeMaster: {
    CENTRAL_SECTOR_INTEREST_SUBSIDY: { id: 1, loanMasterId: 8, name: "Central Sector Interest Subsidy", code: "CSIS", businessTypeId: 9 },
    PADHO_PRADESH: { id: 2, loanMasterId: 8, name: "Padho Pardesh", code: "Padho Pardesh", businessTypeId: 9 },
    DR_AMBEDKAR_CENTRAL_SECTOR_SCHEME: { id: 3, loanMasterId: 8, name: "Dr. Ambedkar Central Sector Scheme", code: "DACSS", businessTypeId: 9 },
    PRADHAN_MANTRI_AWAS_YOJANA: { id: 4, loanMasterId: 3, name: "Pradhan Mantri Awas Yojana - Urban", code: "PMAY-U", businessTypeId: 5 },
    PRIME_MINISTER_EMPLOYMENT_GENERATION_PROGRAMME: { id: 5, loanMasterId: 6, name: "Prime Minister's Employment Generation Programme", code: "PMEGP", businessTypeId: 11 },
    AGRICLINICS_AGRIBUSINESS_CENTERS_SCHEME: { id: 6, loanMasterId: 6, name: "Agri Clinics And Agri Business Centers Scheme", code: "ACABC", businessTypeId: 11 },
    AGRICULTURAL_MARKETING_INFRASTRUCTURE: { id: 7, loanMasterId: 6, name: "Agricultural Marketing Infrastructure", code: "AMI", businessTypeId: 11 },
    WEAVER_CREDIT_CARD: { id: 8, loanMasterId: 4, name: "Star Weaver Mudra Scheme", code: "SWMS", businessTypeId: 1 },
    PRADHAN_MANTRI_MUDRA_YOJNA: { id: 9, loanMasterId: 4, name: "Pradhan Mantri MUDRA Yojna", code: "PMMY", businessTypeId: 1 },
    PM_SVANIDHI: { id: 10, loanMasterId: 4, name: 'Pradhan Mantri Street Vendor Aatmanirbhar Svanidhi Scheme', code: 'PM SVANidhi', businessTypeId: 1 },
    NULM: { id: 11, loanMasterId: 12, name: 'Deendayal Antyodaya Yojana-NATIONAL Urban Livelihoods Mission', code: 'DAY-NULM', businessTypeId: 12 },
    SRMS: { id: 12, loanMasterId: 4, name: 'Self Employment Scheme for Rehabilitation of Manual Scavengers', code: 'SRMS', businessTypeId: 1 },
    STAND_UP_INDIA_SCHEME: { id: 13, loanMasterId: 4, name: "Stand Up India Scheme", code: "SUIS", businessTypeId: 1 },
    DEENDAYAL_ANTYODAYA_YOJANA_NATIONAL_RURAL_LIVELIHOODS_MISSION: { id: 14, loanMasterId: 12, name: 'Deendayal Antyodaya Yojana - National Rural Livelihoods Mission', code: 'DAY-NRLM', businessTypeId: 12 },
    AGRICULTURE_INFRASTRUCTURE_FUND: { id: 15, loanMasterId: 6, name: 'Agriculture Infrastructure Fund', code: 'AIF', businessTypeId: 11 },
    KCC: { id: 16, loanMasterId: 9, name: 'Kisan Credit Card', code: 'KCC', businessTypeId: 11 },
    SOLAR: { id: 18, loanMasterId: 10, name: 'Solar Rooftop Financing', code: 'SOLAR', businessTypeId: 15 },
    KCCFIM: { id: 19, loanMasterId: 9, name: 'Kisan Credit Card-Fisheries', code: 'KCCFIM', businessTypeId: 11 },
    NWR_AGRI: { id: 20, name: 'e-Kisan Upaj Nidhi', code: 'EKUN' },
  },
  schemeList: [
    { id: -1, name: 'All Scheme', code: 'All' },
    { id: 1, name: 'Central Sector Interest Subsidy', code: 'CSIS' },
    { id: 2, name: 'Padho Pardesh', code: 'Padho Pardesh' },
    { id: 3, name: 'Dr. Ambedkar Central Sector Scheme', code: 'Dr.Ambedkar' },
    { id: 4, name: 'Pradhan Mantri Awas Yojana - Urban', code: 'PMAY-U' },
    { id: 5, name: 'Prime Minister\'s Employment Generation Program', code: 'PMEGP' },
    { id: 6, name: 'Agriclinics And Agribusiness Centers Scheme', code: 'ACABC' },
    { id: 7, name: 'Agricultural Marketing Infrastructure', code: 'AMI' },
    { id: 8, name: 'Weaver Mudra Scheme', code: 'WMS' },
    { id: 9, name: 'Pradhan Mantri MUDRA Yojna', code: 'PMMY' },
    { id: 10, name: 'Pradhan Mantri Street Vendor Aatmanirbhar Svanidhi Scheme', code: 'PM SVANidhi' },
    { id: 11, name: 'Deendayal Antyodaya Yojana-NATIONAL Urban Livelihoods Mission', code: 'DAY-NULM' },
    { id: 12, name: 'Self Employment Scheme for Rehabilitation of Manual Scavengers', code: 'SRMS' },
    { id: 13, name: 'Stand Up India Scheme', code: 'SUIS' },
    { id: 14, name: 'Deendayal Antyodaya Yojana - National Rural Livelihoods Mission', code: 'DAY-NRLM' },
    { id: 15, name: 'Agriculture Infrastructure Fund', code: 'AIF' },
    { id: 16, name: 'Kisan Credit Card', code: 'KCC' },
    { id: 18, name: 'Solar Rooftop Financing', code: 'SOLAR' },
    { id: 19, name: 'Kisan Credit Card-Fisheries', code: 'KCCFIM' },
    { id: 20, name: 'e-Kisan Upaj Nidhi', code: 'EKUN' },

  ],
  BANK_STATEMENT_DURATION_TYPE: {
    SIX_MONTH: { id: 1, name: 'Last 6 months', value: 6 },
    TWELVE_MONTH: { id: 2, name: 'Last 12 months', value: 12 }
  },

  pageMaster: {
    EXISTING_PORTFOLIO: 1,
    FIRM_PROFILE: 2,
    OPPORTUNITY: 3,
    MCA_FINANCIAL: 4,
    RISK_ALERTS: 5,
    NETWORK: 6,
    ANALYTICS: 7,
    GST_ANALYSIS: 8,
    BANK_STATEMENT_ANALYSIS: 9,
    EXIM_ANALYSIS: 10,
    COMMERCIAL_BUREAU: 11,
    CONSUMER_BUREAU: 12,
    COMING_SOON: 13,
    SPREADING: 14,
    SCT_PROJECTIONS: 15,
    EWS_ALERTS: 16,
    DOWNLOADS: 17,
    RENTAL: 18,
    ESCROWS: 19,
    AMT: 20,
    STARTUPS: 21,
    EBV: 22,
    TARGETS_AND_PROSPECTS: 23,
    PRE_APPROVED_PRODUCTS: 35,
    IN_PROCESS_APPLICATION: 36,
    COMPLETED_APPLICATION: 37,
    CONFIGURATIONS: 38,
    ANALYTICS2: 39,
    GST_ANALYSIS2: 40,
    BANK_STATEMENT_ANALYSIS2: 41,
    EXIM_ANALYSIS2: 42,
    COMMERCIAL_BUREAU2: 43,
    CONSUMER_BUREAU2: 44,
    EXIM_DATA: 45,
    EXIM_INTERNAL_DATA: 45,
    CUSTOMER_MASTER: 46,
    USER_MANAGEMENT: 47,
    CUSTOMER_SEGEMENTATION: 48,
    USER_GROUPS_ROLE_MASTER: 49,
    USER_LIST: 50,
    USER_REPORTS: 156,
    TARGET_TRACKING: 157,
    AGEING_REPORT: 158,
    TAT_REPORT: 159,
    BULK_UPLOAD: 51,
    // CUSTOMER_SEG_BULK_UPLOAD: 52,
    COMMERCIAL_CIBIL: 52,
    HRMS_DATA: 53,
    PRE_APPROVED_BULK_UPLOAD: 54,
    SELECT_BANKER_DASHBOARD: 55,
    REGION_MASTER: 56,
    API_MONITORING: 57,
    CUSTOMER_SEG_MASTER: 58,
    API_STATUS: 59,
    FIND_PROSPECT: 60,
    STANDALONE: 61,
    CONSOLIDATED: 62,
    DIRECTORS_CONNECTED_LENDING: 63,
    SHAREHOLDING_RELATED_ENTITIES: 64,
    PEERS: 65,
    COUNTER_PARTIES: 66,
    CUSTOMER_PROFILE: 67,
    ALERT_DESCRIPTION: 68,
    CONTACT_DETAILS: 69,
    FIRM_PROFILE_API_STATUS: 70,
    HSBC_PRE_QUALIFIED_PRODUCTS: 71,
    ALERTS: 72,
    REVENUE_CURRENT_YEAR: 73,
    REVENUE_LAST_YEAR: 74,
    ASSETS: 75,
    LIABILITIES: 76,
    EXIM: 77,
    WPB_REFERRAL: 78,
    NETWORK_DUPLICATE: 79,
    INDIVIDUAL_GST: 80,
    SUMMARY: 81,
    SALES_ANALYSIS: 82,
    PURCHASE_ANALYSIS: 83,
    CONSOLIDATED_GST: 84,
    SUMMARY_INFO: 85,
    MONTHWISE_DETAILS: 86,
    TOP_TRANSACTIONS: 87,
    BOUNCED_CHEQUE: 88,
    TRANSACTIONS: 89,
    EOD_BALANCES: 90,
    EXPORT_WALLET: 91,
    IMPORT_WALLET: 92,
    SAME_BUYER_PEER: 93,
    SAME_SELLER_PEER: 94,
    PRODUCT_EXPORT_PEER: 95,
    PRODUCT_IMPORT_PEER: 96,
    NEW_BUYER: 97,
    NEW_SELLER: 98,
    SEARCH_BY_ANCHOR: 99,
    EXPORT_COUNTRY_EXPOSURE: 100,
    IMPORT_COUNTRY_EXPOSURE: 101,
    SEARCH_BY_PRODUCT: 102,
    SALES_ANALYSIS_CONSOLIDATED: 103,
    SUMMARY_CONSOLIDATED: 104,
    PURCHASE_ANALYSIS_CONSOLIDATED: 105,
    SUMMARY_EXIM: 106,
    API_COUNTER: 107,
    BANK_PORTFOLIO_UPLOAD: 108,
    PRE_SCREEN_DATA: 109,
    REQUESTED_PORTFOLIO: 110,
    PRE_SCREEN: 111,
    PROSPECT_CUSTOMER: 112,
    BANK_STATEMENT_INTERNAL: 113,
    CUSTOMER_RM_MAPPING: 114,
    NEW_FDI: 115,
    NEW_ODI: 116,
    NEW_ECB: 117,
    HSBC_STATUS: 118,
    NEW_INCORPORATION: 119,
    REJECTED_PORTFOLIO: 120,
    CONFIGURATIONS_SUB: 121,
    PORTFOLIO: 122,
    ABB_OF_CURRENT_ACCOUNT_AND_TD: 123,
    CUSTOMER_INCOME: 124,
    PORTFOLIO_ANALYSIS: 125,
    BANK_STATEMENT_ANALYSIS_PORT: 126,
    AVERAGE_BANK_BALANCE_ANALYSIS: 127,
    NEW_AGE_ECONOMY: 133,
    LEADING_IDICATORS: 134,
    INVESTORS: 135,
    FACILITORS: 136,
    NEW_AGE_ECONOMY_TAB: 137,
    KEY_INSIGHTS_TAB: 138,
    COMPETITION_AND_ECOSYSTEM_TAB: 139,
    LEANDING_INDICATOR_TAB: 140,
    BANK_PORTFOLIO_UPLOAD_ONE_TIME: 142,
    INDUSTRY_BANCHMARK_RATING: 143,
    FILTER_MONITORING: 145,
    CONSUMER_CIBIL: 147,
    NEW_GCC: 130,
    MONITORING: 160,
    PRODUCT_APPROVAL_JOURNEY: 165,
    PR_DASHBOARD: 167,
    OPPORTUNITY_DASHBOARD: 174,
    EXIM_EXTERNAL_DATA: 179,
    INCOME_DATA_UPLOAD: 180,
    INCOME_DASHBOARD: 181,
    EXIM_EXCHANGE_RATE: 182,
    EXIM_UPLOADS: 186,
    DIRECTORS_CONTACT_DETAILS: 187,
    CAMPAIGN_DASHBOARD: 306,
    ETB_CAMPAIGN_DASHBOARD: 307,
    NTB_CAMPAIGN_DASHBOARD: 308,
    HELP_AND_SUPPORT_UPLOAD: 313,
    HELP_AND_SUPPORT: 314,
    FINANCIALS_ANALYSIS: 317,
    CREDIT_AND_BUREAU: 318,
    API_RELATED: 319,
    PORTFOLIO_NEW: 320,
    CRIF_DATA_UPLOAD: 321,
    HELP_AND_SUPPORT_SUBPAGE: 315,
    COMMERCIAL_SUMMARY: 323,
    CORPORATE_ANNOUNCEMENTS: 324,
    CRILC_DATA_UPLOAD: 325
  },



  ReportType: {
    SEGMENT_WISE_ALL: 1,
    SEGMENT_WISE_SEGMENT_SELECTED: 2,
    SEGMENT_WISE_SEGMENT_CITY_SELECTED: 3,
    SEGMENT_WISE_SEGMENT_CITY_RM_SELECTED: 4,
    CITY_WISE_OVERALL: 5,
    CITY_WISE_CITY_SELECTED: 6,
    CITY_WISE_RM_SELECTED: 7,
    RM_WISE_OVERALL: 8,
    RM_WISE_RM_SELECTED: 9,
    CUSTID_WISE_OVERALL: 10,
    CUSTID_WISE_SELECTED: 11
  },

  PageActions: {
    VIEW: 1,
    EDIT: 2,
    DOWNLOAD: 3,
    SEARCH: 4,
    UPLOAD: 5,
    AUDIT: 6,
    FILTER_SELECTION: 7,
    PAGE_VIEW_SELECTION: 8,
    REFRESH: 9,
    DATE_SELECTION: 10,
    DOWNLOAD_TEMPLATE: 11,
    DOWNLOAD_SUCCESS_ENTRY: 12,
    DOWNLOAD_FAIL_ENTRY: 13,
    DOWNLOAD_TOTAL_ENTRY: 14,
    FILTER: 15,
    CLEAR_FILTERS: 16,
    DELETE: 17,
    FIND_PROSPECTS: 18,
    ADD_NEW_CUSTOMER: 19,
    MANAGE_PERMISSION: 20,
    SPREAD_ORDER: 21,
    ORDER_FINANCIAL: 22,
    COMPLETE_APPLICATION: 23,
    START_PRE_APPROVAL: 24,
    DOWNLOAD_TOTAL_INACTIVE_USER: 25,
    DOWNLOAD_ALL_CUSTOMERS: 26,
    DOWNLOAD_CUSTOMER_OF_DISABLED_RM: 27,
    DOWNLOAD_ALL_HRMS_DATA: 28,
    DOWNLOAD_ALL_REGION: 29,
    DOWNLOAD_ALL_CUSTOMER_SEGMENT: 30,
    TOPBAR_FILTER: 31,
    EXPORT: 32,
    ASSIGN_USER: 33,
    TOPBAR_FILTER_RM: 34,
    TOPBAR_FILTER_CITY: 35,
    TOPBAR_FILTER_SEGMENT: 36,
    TOPBAR_FILTER_REGION: 37,
    TOPBAR_FILTER_RESET: 38,
    TOPBAR_FILTER_CATEGORY: 39,
    INDUSTRY: 40,
    SECTOR: 41,
    TURNOVER: 42,
    LATEST_CREDIT_RATING: 43,
    CDD: 44,
    ADDRESS_DETAILS: 45,
    CONTACT_PERSON: 46,
    GOODS_EXPORT: 47,
    SERVICE_EXPORT: 48,
    DATE_OF_BALANCE_SHEET: 49,
    NAME_OF_AUDITOR: 50,
    TURNOVER_FOR_FY: 51,
    PROFIT_AND_LOSS: 52,
    BALANCE_SHEET: 53,
    RATIO_IN_DAYS: 54,
    RATIO_IN_TIMES: 55,
    ALERTS: 56,
    DETAILS: 57,
    DIRECTOR_DETAILS: 58,
    EXCO_DETAIL: 59,
    CONNECTED_LENDING_DETAILS: 60,
    SHAREHOLDING_PATTERN: 61,
    DETAILED_SHAREHOLDING: 62,
    RELATED_ENTITIES: 63,
    INDUSTRY_PEERS: 64,
    TOP_5_EXPORT: 65,
    TOP_5_IMPORT: 66,
    TOP_5_BUYER: 67,
    TOP_5_SELLER: 68,
    TOP_5_FUND_PAYMENT: 69,
    TOP_5_FUND_RECEIPT: 70,
    VIEW_MORE: 71,
    SUMMARY_OF_GST: 72,
    OVERALL_GST_SUMMARY: 73,
    GSTIN_SALES_AND_PURCHASE: 74,
    TOTAL_GSTIN: 75,
    COMPANY_DETAILS: 76,
    GST_SUMMARY_DATA: 77,
    ANNUAL_TURNOVER: 78,
    QUARTERLY_TURNOVER_PROJECTED: 79,
    QUARTERLY_TURNOVER: 80,
    SALES_VS_TOTAL_SALES: 81,
    SALES_GROWTH_QTR_TO_QTR: 82,
    HSN_SUMMARY: 83,
    TOP_50_BUYERS: 84,
    NEW_BUYERS_THIS_YEAR: 85,
    LOST_BUYERS_LAST_YEAR: 86,
    TURNOVER_BY_CATEGORY_PERCENT: 87,
    TURNOVER_RECONCILIATION: 88,
    QUARTERLY_PURCHASE: 89,
    PURCHASE_GROWTH_QTR_TO_QTR: 90,
    TOP_SELLERS: 91,
    QUARTERLY_GROSS_MARGIN: 92,
    SUMMARY_INFO: 93,
    BANK_BALANCE_SUMMARY: 94,
    CREDIT_SUMMARY: 95,
    DEBIT_SUMMARY: 96,
    MONTHWISE_DETAILS: 97,
    TOP_FUND_PAYMENT: 98,
    TOP_FUND_RECEIVED: 99,
    STATEMENT_XNS: 100,
    DAYWISE_DETAILS: 101,
    SUMMARY: 102,
    EXIM_SUMMARY: 103,
    EXPORT_DETAILS: 104,
    IMPORT_DETAILS: 105,
    SAME_BUYER_PEER: 106,
    SAME_SELLER_PEER: 107,
    PRODUCT_EXPORT_PEER: 108,
    PRODUCT_IMPORT_PEER: 109,
    NEW_BUYER: 110,
    NEW_SELLER: 111,
    SEARCH_BY_ANCHOR: 112,
    EXPORT_COUNTRY_EXPOSURE: 113,
    IMPORT_COUNTRY_EXPOSURE: 114,
    SEARCH_BY_PRODUCT: 115,
    SHIPMENT_DETAILS: 116,
    CMR_SCORE: 117,
    BUREAU_VINTAGE: 118,
    TOTAL_LENDERS: 119,
    BORROWER_DETAILS: 120,
    DPD_DETAILS: 121,
    OVERALL_DETAILS: 122,
    TREND_ANALYTICS: 123,
    PRODUCT_WISE_DETAILS: 124,
    DEFAULT_DATA: 125,
    BUREAU_SCORE: 126,
    BUREAU_VINTAGE_DUPLICATE: 127,
    TOTAL_NO_OF_OPEN_ACCOUNTS: 128,
    DETAILS_OF_SPECIFIC_LOAN_TYPES: 129,
    NO_OF_NEW_LOANS: 130,
    BASIC_DETAILS: 131,
    DEFAULT_DATA_OF_LAST_24_MONTHS: 132,
    HSBC_CLOSED_FACILITY: 133,
    ADD_NEW: 134,
    TOPBAR_FILTER_COUNTRIES: 135,
    DOWNLOAD_ALL_PRE_SCREEN_DATA: 136,
    TOPBAR_FILTER_PINCODE: 137,
    UPDATE: 138,
    MASK_PAN: 139,
    ACTIVE_INAVTIVE: 140,
    TOPBAR_FILTER_LOCATION: 141,
    REJECT_CUSTOMER: 142,
    SUPPLIER_LIST: 143,
    CUSTOMER_LIST: 144,
    PAYMENT_IN: 145,
    PAYMENT_OUT: 146,
    SELF_TRANSFER: 147,
    CURRENT_ACCOUNT_AVG_BALANCE: 148,
    TERM_DEPOSIT_BALANCE: 149,
    AVG_BALANCE_EEFC: 150,
    LEADING_INDICATOR: 154,
    INVESTOR: 155,
    FACILITORS: 156,
    ORDER_CRISIL: 157,
    PEER_COMPARASION: 158,
    COMPANAY_LEVEL_RATING: 159,
    BANKER_LEVELE_RATING: 160,
    DOWNLOAD_CUSTOMER_RM: 163,
    DIN_TO_PAN_REFTESH: 177,
    EDIT_CAMPAIGN: 178,
    CREATE_CAMPAIGN: 183,
    SHARE_TO_RM: 185,
    CHANGE_STATUS: 186,
    MARK_IN_ACTIVE: 187,
    COMPARISON_VIEW: 188,
    COMPARISON_EXCEL_DOWNLOAD: 189,
    SUMMARY_EXCEL_DOWNLOAD: 190,
    UN_MASK_CONTACT_NO: 201,
    CUSTOMER_CHILD_BULK_UPLOAD: 204,
    DOWNLOAD_ALL_CHILD_CUSTOMERS: 205,
    DOWNLOAD_FINANCIALS: 310,
    CLIENT_UPDATE: 311,
    CUSTOMER_REJECTION_REASONS: 312,
    THRESHOLD_CONFIGURE: 313,
    RF_CONFIGURATIONS: 320,
    DOWNLOAD_ALL_COUNTRY: 322,
  },

  ACTION_BUTTON_MASTER: {
    EDIT: 1,
    DELETE: 2,
    LOCK_UNLOCK: 3,
    RESET_PASSWORD: 4,
    ACTIVE_INACTIVE: 5,
    MANAGE_PERMISSION: 6,
  },
  Role: {
    HEAD_OFFICER: 5,
    HEAD_OFFICER_USER_MANAGEMENT: 6,
    BRANCH_MAKER: 8,
    BRANCH_CHECKER: 9,
    ADMIN_MAKER: 10,
    ADMIN_CHECKER: 11,
    ZO_MAKER: 13,
    ZO_ADMIN: 803,
    CO_MAKER: 15,
    PLP_CHECKER_80LAKHS: 18,
    PLP_CHECKER_1CR: 19,
    PARTNER: 710,
    LEAD_GENERATOR: 711,
    BORROWER_ASSISTANCE: 712,
    LSP_USER: 806,
    ANCHOR_USER: 807,
    SUPER_ADMIN: 811,
    HO_ADMIN: 800,
    USER: 30
  },
  BranchType: {
    Branch_Office: 1,
    Regional_Office: 2,
    Zonal_Office: 3
  },
};
export const AuditAPIType = {
  API_AUDIT: { value: 'API_AUDIT', displayValue: 'API Audit Log' },
  PRE_APPROVED_API_AUDIT: { value: 'PRE_APPROVED_API_AUDIT', displayValue: 'API Audit Log' },
  // MCA_ADUIT: { value: 'MCA_ADUIT', displayValue: 'MCA Aduit' },
  CIBIL_ADUIT: { value: 'CIBIL_ADUIT', displayValue: 'CIBIL Aduit Log' },
  // Guest: { value: 'GUEST', displayValue: 'Guest User' }
} as const;

export type AaduitAPIType = keyof typeof AuditAPIType;

export enum ShareholdingType {
  INDIVIDUAL_HINDU_INDIVIDUAL_FAMILY = 'INDIVIDUAL_HINDU_INDIVIDUAL_FAMILY',
  INDIAN = 'INDIAN',
  NON_RESIDENT_INDIAN_NRI = 'NON_RESIDENT_INDIAN_NRI',
  FOREIGN_NATIONAL_OTHER_THAN_NRI = 'FOREIGN_NATIONAL_OTHER_THAN_NRI',
  GOVERNMENT = 'GOVERNMENT',
  CENTRAL_GOVERNMENT = 'CENTRAL_GOVERNMENT',
  STATE_GOVERNMENT = 'STATE_GOVERNMENT',
  GOVERNMENT_COMPANIES = 'GOVERNMENT_COMPANIES',
  BANKS = 'BANKS',
  BODY_CORPORATE = 'BODY_CORPORATE',
  FINANCIAL_INSTITUTIONS = 'FINANCIAL_INSTITUTIONS',
  FOREIGN_INSTITUTIONAL_INVESTORS = 'FOREIGN_INSTITUTIONAL_INVESTORS',
  INSURANCE_COMPANIES = 'INSURANCE_COMPANIES',
  MUTUAL_FUNDS = 'MUTUAL_FUNDS',
  OTHERS = 'OTHERS',
  TOTAL = 'TOTAL',
  TOTAL_NO_OF_SHAREHOLDERS = 'TOTAL_NO_OF_SHAREHOLDERS',
  VENTURE_CAPITAL = 'VENTURE_CAPITAL'
}

// Optionally, you can map it to display names
export const ShareholdingTypeDisplay: Record<ShareholdingType, string> = {
  [ShareholdingType.INDIVIDUAL_HINDU_INDIVIDUAL_FAMILY]: "Individual/Hindu Individual Family",
  [ShareholdingType.INDIAN]: "(i) Indian",
  [ShareholdingType.NON_RESIDENT_INDIAN_NRI]: "(ii) Non-resident Indian (NRI)",
  [ShareholdingType.FOREIGN_NATIONAL_OTHER_THAN_NRI]: "(iii) Foreign national (other than NRI)",
  [ShareholdingType.GOVERNMENT]: "Government",
  [ShareholdingType.CENTRAL_GOVERNMENT]: "(i) Central Government",
  [ShareholdingType.STATE_GOVERNMENT]: "(ii) State Government",
  [ShareholdingType.GOVERNMENT_COMPANIES]: "(iii) Government companies",
  [ShareholdingType.BANKS]: "Banks ",
  [ShareholdingType.BODY_CORPORATE]: "Body corporate",
  [ShareholdingType.FINANCIAL_INSTITUTIONS]: "Financial institutions",
  [ShareholdingType.FOREIGN_INSTITUTIONAL_INVESTORS]: "Foreign institutional investors",
  [ShareholdingType.INSURANCE_COMPANIES]: "Insurance companies",
  [ShareholdingType.MUTUAL_FUNDS]: "Mutual funds",
  [ShareholdingType.OTHERS]: "Others",
  [ShareholdingType.TOTAL]: "Total",
  [ShareholdingType.TOTAL_NO_OF_SHAREHOLDERS]: "Total No. of Shareholders",
  [ShareholdingType.VENTURE_CAPITAL]: "Venture capital",

};

export enum TracxnFileAndTabCategory {
  LEADING_INDICATOR = 'LEADING_INDICATOR',
  INVESTOR = 'INVESTOR',
  FACILITATOR = 'FACILITATOR',
  FACILITATOR_LIST = 'FACILITATOR_LIST',
  FACILITATOR_DEALS = 'FACILITATOR_DEALS',
}

export enum NewAgeEconomySubTab {
  KEY_INSIGHTS = 'Key Insights',
  COMPETITION_AND_ECOSYSTEM = 'Competition & Ecosystem',
  LEADING_INDICATORS = 'Leading Indicators'
}

export interface SchedularTypeOption {
  id: number;
  key: string;
  label: string;
}
export const SCHEDULAR_TYPES: SchedularTypeOption[] = [
  {
    id: null,
    key: 'ALL',
    label: 'All'

  },
  {
    id: 1,
    key: 'FILTER',
    label: 'Filter Daily'

  },
  {
    id: 2,
    key: 'EXIM_MONTHLY_SCHEDULER',
    label: 'EXIM ETB Periodically'
  },
  {
    id: 3,
    key: 'KARZA_GST_MONTHLY_SCHEDULER',
    label: 'GST ETB Periodically'
  },
  {
    id: 4,
    key: 'KARZA_UDYAM_MONTHLY_SCHEDULER',
    label: 'UDYAM ETB Periodically'
  },
  {
    id: 5,
    key: 'KARZA_UDYAM_CERT_MONTHLY_SCHEDULER',
    label: 'UDYAM Certificate ETB Periodically'
  },
  {
    id: 6,
    key: 'EXIM_MONTHLY_SCHEDULER_TARGET',
    label: 'EXIM Target Periodically'
  },
  {
    id: 7,
    key: 'KARZA_GST_MONTHLY_SCHEDULER_TARGET',
    label: 'GST Target Periodically'
  },
  {
    id: 8,
    key: 'KARZA_UDYAM_MONTHLY_SCHEDULER_TARGET',
    label: 'UDYAM Target Periodically'
  },
  {
    id: 9,
    key: 'KARZA_UDYAM_CERT_MONTHLY_SCHEDULER_TARGET',
    label: 'UDYAM Certificate Target Periodically'
  },
  {
    id: 10,
    key: 'EXIM_MONTHLY_SCHEDULER_PROSPECT',
    label: 'EXIM Prospect Periodically'
  },
  {
    id: 11,
    key: 'KARZA_GST_MONTHLY_SCHEDULER_PROSPECT',
    label: 'GST Prospect Periodically'
  },
  {
    id: 12,
    key: 'KARZA_UDYAM_MONTHLY_SCHEDULER_PROSPECT',
    label: 'UDYAM Prospect Periodically'
  },
  {
    id: 13,
    key: 'KARZA_UDYAM_CERT_MONTHLY_SCHEDULER_PROSPECT',
    label: 'UDYAM Certificate Prospect Periodically'
  },
  {
    id: 14,
    key: 'EXIM_DAILY_SCHEDULER',
    label: 'EXIM Daily'
  },
  {
    id: 15,
    key: 'GST_DAILY_SCHEDULER',
    label: 'GST Daily'
  },
  {
    id: 16,
    key: 'UDYAM_DAILY_SCHEDULER',
    label: 'Udyam Daily'
  },
  {
    id: 17,
    key: 'UDYAM_CERT_DAILY_SCHEDULER',
    label: 'Udyam Certificate Daily'
  },
  {
    id: 18,
    key: 'TRACXN_MONTHLY_SCHEDULER',
    label: 'TRACXN ETB Periodically'
  },
  {
    id: 19,
    key: 'TRACXN_MONTHLY_SCHEDULER_TARGET',
    label: 'TRACXN Target Periodically'
  },
  {
    id: 20,
    key: 'TRACXN_MONTHLY_SCHEDULER_PROSPECT',
    label: 'TRACXN Prospect Periodically'
  },
  {
    id: 21,
    key: 'MCA_ETB_SYNC',
    label: 'MCA Bulk Etb Sync'
  },
  {
    id: 22,
    key: 'MCA_ETB_ASYNC',
    label: 'MCA Bulk Etb Async'
  },

  {
    id: 23,
    key: 'MCA_NEW_ECB',
    label: 'MCA New ECB Dashboard'
  },
  {
    id: 24,
    key: 'MCA_NEW_FDI_ODI',
    label: 'MCA New FDI And ODI Dashboard'
  },

  {
    id: 25,
    key: 'MCA_NEW_INCORPORATION',
    label: 'MCA New Incorporation'
  },
  {
    id: 26,
    key: 'MCA_TRACK_IT',
    label: 'MCA TrackIt'
  },
  {
    id: 27,
    key: 'MCA_DIRECTOR_DIN_TO_PAN',
    label: 'MCA Director DIN TO PAN'
  },
  {
    id: 28,
    key: 'PAN_TO_CIN_CUSTOMER',
    label: 'Pan to CIN Customer'
  },
  {
    id: 29,
    key: 'TRACK_FDI_ODI',
    label: 'Track FDI ODI ECB'
  },
  {
    id: 30,
    key: 'CRISIL_NOT_IN_COVERAGE',
    label: 'Crisil Not In Coverage Scheduler'
  },
  {
    id: 31,
    key: 'REQUEST_EXPIRY_PORTFOLIO_RELEASE',
    label: 'Release Expired Request'
  },
  {
    id: 32,
    key: 'CRISIL_BULK_QUARTERLY',
    label: 'Fetch BULK Data Quarterly'
  },
  {
    id: 33,
    key: 'CRISIL_BULK_FORTNIGHTLY',
    label: 'Fetch BULK Data Fortnightly'
  },
  {
    id: 35,
    key: "OD_INITIATE_PRE_APPROVED_JOURNEY",
    label: "Initiate Pre-Approved Journey"
  }
  ,
  {
    id: 36,
    key: "OD_GET_STATUS_FOR_PRE_APPROVED_PRODUCTS",
    label: "Get Response for Pre-Approved Products"
  },
  {
    id: 37,
    key: "EXPIRE_APPLICATION",
    label: "Expire Pre-Approved Journey applications that exceed the configured expiry days"
  },
  {
    id: 38,
    key: "MCA_PROSPECT_SYNC",
    label: "Used to call MCA Bulk Prospect Sync Dashboard"
  },
  {
    id: 39,
    key: "MCA_PROSPECT_ASYNC",
    label: "Used to call MCA Bulk Prospect Sync Dashboard"
  },
  {
    id: 42,
    key: "MCA_CORPORATE_ANNOUNCEMENT",
    label: "Used to call MCA Bulk MCA Corporate Announcement"
  },
  {
    id: 43,
    key: "INDUSTRY_NEWS",
    label: "Used to call Industry News Dashboard"
  }

];

export const CibilUploadTypes = {
  UPLOAD_PR: 1,
  UPLOAD_PR_STATUS: 2,
  UPLOAD_SELECTED_CUSTOMER: 3,
  UPLOAD_ALL_CUSTOMER: 4,
  UPLOAD_INPUTFILE: 5,
};

export const CibilDownloadUrls = {
  DOWNLOAD_PRSTATUS_DATA: '/start/bulkupload/download_prstatus_data/?file_id=',
  DOWNLOAD_CIBILINPUTDATA: '/start/bulkupload/download_cibilinputdata/?file_id=',
  DOWNLOAD_UPLOADEDCUSTOMER_DATA: '/start/bulkupload/download_uploadedcustomer_data/?file_id=',
  DOWNLOAD_INPUTFILE_DATA: '/start/bulkupload/download_inputfiledata/?file_id=',
  RECONSILATION_DOWNLOAD: '/start/bulkupload/cibil_reconciliation/?file_id=',
  };

export const CrifDownloadUrls = {
  DOWNLOAD_UPLOADEDCUSTOMER_DATA: '/download_customer_uploaded_file?file_id=',
};

export const ConsumerCibilDownloadUrls = {
  DOWNLOAD_PRSTATUS_DATA: '/consumer_bureau/download_prstatus_data/?file_id=',
  DOWNLOAD_CIBILINPUTDATA: '/consumer_bureau/download_cibilinputdata/?file_id=',
  DOWNLOAD_UPLOADEDCUSTOMER_DATA: '/consumer_bureau/download_uploadedcustomer_data/?file_id=',
};


export enum HsnCodeLength {
  TWO = 2,
  FOUR = 4,
  SIX = 6,
}

export const CUSTOMIZE_COLUMN = {
  "Id": "id",
  "Customer ID": "customerId",
  "Name Of Customer": "name",
  'HSBC Wallet': 'hsbcwallet',
  'Total Opportunity': 'totalOpportunity',
  'Share (%)': 'share',
  'Pre-Qualified': 'preApproved',
  "Customer type": "customerType",
  "Country": "country",
  "Global RM": "globalRm",
  "Parent Company Name": "parentCompanyName",
  "Assignment Source": "assignmentSource",
  "PAN": "panNo",
  "CRR": "crr",
  'City': 'city',
  'Subsidiary Country': 'subsidiaryCountry',
  'Subsidiary Company': 'subsidiary',
  'Segment': 'segment',
  'Period': 'period',
  'USD in Million': "usdAmount",
  'country': 'countryName',
  'USD In Million': 'total',
  'Entity Name': 'entityName',
  'Type': "type",
  'period': 'month',
  'Amount USD M': 'usdAmount',
  'Lender Category': 'lenderCategory',
  'Purpose': 'purpose',
  'Maturity': 'maturityPeriod',
  'Foreign Collaborator': 'foreignCollaborator',
  'Route': 'route',
  "RM PS ID": "rmId",
  "RM name": "rmName",
  "IEC": "ieCode",
  "CIN": "cin",
  "CDD Date": "cddReviewDate",
  "GST Status": "gstStatus",
  "Date of Incorporation": "dateOfIncorporation",
  "LEI Number": "leiNumber",
  "LEI Expiry": "leiExpiry",
  "Listing status": "listingStatus",
  "No. of employees": "noOfEmployee",
  "Business": "business",
  "Last approved date": "lastApprovedDate",
  "Time With HSBC": "timeWithHsbc",
  "Latest audited year": "dateOfBalanceSheet",
  "Auditor Turnover": "auditedTurnover",
  "IT/ITES Turnover": "IT_ITEsTurnover",
  "EBIDTA": "ebitda",
  "EBIDTA%": "ebitdaMarginPer",
  "PAT": "pat",
  "PAT%": "patPer",
  "Trade receivables": "tradeReceivables",
  "Inventories": "inventories",
  "Non current assets": "nonCurrentAsset",
  "Total Asset": "totalAsset",
  "Net worth": "netWorth",
  "Trade Payable": "tradePayables",
  "Long term borrowings": "longTermBorrowings",
  "Short term borrowings": "shortTermBorrowings",
  "Leverage": "leverage",
  "Net debt/EBITDA": "netDebtEbita",
  "Working capital cycle": "workingCapitalCycle",
  "Current ratio": "currentRatio",
  "DSCR": "dscr",
  "Interest coverage ratio": "interestCoverageRatio",
  "Cash and Bank": "currentAccountBalance",
  "Current investments": "currentInvestments",
  "Annual Tax": "annualTax",
  "Annual Salary": "annualSalary",
  "Unbilled Revenue (Rs. in Cr.)": "unbilledRevenue",
  "Dividend paid (Rs. in Cr.)": "dividendPaid",
  "Dividend Payable (Rs. in Cr.)": "dividendPayable",
  "CSR obligation (Rs. in Cr.)": "csrObligation",
  "CSR Amount Spent (Rs. in Cr.)": "csrAmountSpent",
  "Transfer to unspent CSR A/c (Rs. in Cr.)": "transferToUnspentCsrAc",
  "Credit Churn(Current FY)": "percentageOfChurnCy",
  "Credit Churn(Previous FY)": "percentageOfChurnPy",
  "Open charges": "countOfOpenCharges",
  "Date of bureau report": "dateOfBureauFetch",
  "CMR score": "cmrScoreValue",
  "Total Sanction": "sanctionAmt",
  "Total Utilization": "outstandingAmt",
  "HSBC Sanction": "sanctionWallet",
  "HSBC Utilization": "utilizationWallet",
  "Facilities from Private & Foreign Banks": "noOfLenders",
  "Facilities from NBFC & Others": "noOfFacilityNbfcAndOther",
  "Facilities from NBFC and Other (O/S)": "noOfFacilityNbfcAndOtherOs",
  "Bureau Vintage": "bureauVintage",
  "Exports last 12 months (Units in $)": "eximTotalExport",
  "No. of Export shipment": "eximNoOfExportShipment",
  "Total Imports last 12 months (Units in $)": "eximTotalImport",
  "No. of Import shipment": "eximNoOfImportShipment",
  "ECB (Units in $)": "ecb",
  "FDI (Units in $)": "fdi",
  "ODI (Units in $)": "odi",
  "No. of directors": "noOfDirectors",
  "Director remuneration": "dirRemuneration",
  "LAP Loans": "lapLoans",
  "Home Loans": "homeLoans",
  "Cards": "cards",
  "Udyam": "udyamNumber",
  "Udyam status": "udyamStatus",
  "Udyam category": "udyamCategory",
  "MCA open charge(Rs. in Lacs)": "mcaOpenCharge",
  "Constitution as per MCA": "mcaConstitution",
  "Constitution as per GST": "gstConstitution",
  "Industry": "industry",
  "Sector": "sector",
  "Foreign Shareholding": "foreignShareholding",
  "GST Turnover slab": "gstTurnoverSlab",
  "PSL status": "pslStatus",
  "Agri PSL": "agriPsl",
  "CDD risk rating": "cddRiskRating",
  "Name of auditor": "nameOfAuditor",
  "Latest credit rating":"latestCreditRating",
  "Rating Type":"ratingType",
  "Rating agency":"ratingAgency",
  "Date of rating":"dateOfRating",
  "Payable Days(Sales Basis)":"payableDays",
  "Days Of Sales Outstanding":"daysOfSales",
  "Inventory Days(Sales Basis)":"indentoryDays",
  "Data Source":"dataSource",
  "Sole/Multiple lending":"soleMultipleLending",
  "Next review date":"limitReviewDate"
}
